services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: "summary"
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - summary-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.10
    environment:
      PGADMIN_DEFAULT_EMAIL: "eagle221174@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres
  
  tubes_api:
    container_name: api_tubes
    build:
      context: .
      dockerfile: docker/api_tubes/Dockerfile.prod
      args:
        - NODE_ENV=production
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/tubesdb?schema=public
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "tubes_db"
      PORT: "7100"
    volumes:
      - files-data:/api_tubes/uploads 
    ports:
      - "7100:7100"    
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres
      - general


  # api:
  #   container_name: api_container
  #   build:
  #     context: .
  #     dockerfile: docker/api/Dockerfile.dev
  #     args:
  #       - NODE_ENV=development
  #   environment:
  #     POSTGRESHOST: "postgres"
  #     POSTGRES_PORT: "5432"
  #     POSTGRES_USERNAME: "admin"
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_DB: "summary"
  #     PORT: "7000"
  #   depends_on:
  #     - postgres
  #   restart: always
  #   ports:
  #     - "7000:7000"
  #   networks:
  #     - postgres
  #     - general

  # app:
  #   container_name: app_container
  #   build:
  #     context: .
  #     dockerfile: docker/app/Dockerfile.dev
  #     args:
  #       - NODE_ENV=development
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - general
  
  nginx-file-server:
    container_name: nginx_file_server_container
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.file-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - files-data:/usr/share/nginx/files
    ports:
      - "8080:8080"
    restart: always
    networks:
      - postgres
      - general
    depends_on:
      - postgres

volumes:
  summary-data:
  pgadmin-data:
  files-data:
networks:
  general:
    driver: bridge
  postgres:
    driver: bridge
