services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_DB: "summary"
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - summary-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      PGADMIN_DEFAULT_EMAIL: "eagle221174@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres
    depends_on:
      - postgres

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: docker/api/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "summary"
      PORT: "7000"
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      KLP_TECHNOLOGIST_CHAT_ID: ${KLP_TECHNOLOGIST_CHAT_ID}
      PSK_TECHNOLOGIST_CHAT_ID: ${PSK_TECHNOLOGIST_CHAT_ID}
      KLP_PACKAGING_CHAT_ID: ${KLP_PACKAGING_CHAT_ID}
      PSK_PACKAGING_CHAT_ID: ${PSK_PACKAGING_CHAT_ID}
      MSSQL_HOST: ${MSSQL_HOST}
      MSSQL_USERNAME: ${MSSQL_USERNAME}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres
      - general

  # public_api:
  #   container_name: public_api_container
  #   build:
  #     context: .
  #     dockerfile: docker/public_api/Dockerfile.prod
  #     args:
  #       - NODE_ENV=production
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/summary
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: "5432"
  #     POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: "summary"
  #     PORT: "8000"
  #     BOT_TOKEN: ${BOT_TOKEN}
  #     CHAT_ID: ${CHAT_ID}
  #   depends_on:
  #     - postgres
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - postgres
  #     - general

  public_api:
    container_name: public_api_container
    build:
      context: .
      dockerfile: docker/public_api_2/Dockerfile.prod
      args:
        - NODE_ENV=production
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/summary
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "summary"
      PORT: "8000"
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    depends_on:
      - postgres
    restart: always
    ports:
      - 8000:8000
    networks:
      - postgres
      - general
  
  tubes_api:
    container_name: api_tubes
    build:
      context: .
      dockerfile: docker/api_tubes/Dockerfile.prod
      args:
        - NODE_ENV=production
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/tubesdb?schema=public
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "tubes_db"
      PORT: "7100"
    volumes:
      - files-data:/api_tubes/uploads 
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres
      - general

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: docker/application/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - api
    restart: always
    networks:
      - general

  workstation:
    container_name: ws_container
    build:
      context: .
      dockerfile: docker/workstation/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - api
    restart: always
    networks:
      - general

  tubes_dash:
    container_name: tubes_dash
    build:
      context: .
      dockerfile: docker/tubes/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - tubes_api
    restart: always
    networks:
      - general
  
  dash:
    container_name: dash_container
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - api
    restart: always
    networks:
      - general

  nginx:
    container_name: nginx_container
    build: ./docker/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    ports:
      - "80:80"
      - "3000:3000" 
      - "3100:3100"
      - "5000:5000"
    networks:
      - general
    depends_on:
      - app
      - workstation

  nginx-file-server:
    container_name: nginx_file_server_container
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.file-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - files-data:/usr/share/nginx/files
    ports:
      - "8080:8080"
    restart: always
    networks:
      - postgres
      - general
    depends_on:
      - postgres

volumes:
  summary-data:
  pgadmin-data:
  files-data:

networks:
  general:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
